# --- HYPRLAND F1 EDITION ---

# 1. MONITEURS
monitor=,highres,auto,1

# 2. AUTO-START
exec-once = swww-daemon
exec-once = sleep 1 && swww img /home/monuser/wallpapers/carbon.jpg
exec-once = waybar
# Agent d'authentification (pour que Sublime Text/GUI demande le mdp)
exec-once = /run/current-system/sw/libexec/polkit-gnome-authentication-agent-1

# 3. INPUT
input {
    kb_layout = fr, it
    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

#layout clavier logitech mx keys
device {
	name = logitech-mx-keys
	kb_layout = it
}
# 4. LOOK & FEEL
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    
    # Bordure fenetre
    col.active_border = rgb(00a19c)
    col.inactive_border = rgb(1a1a1a)

    layout = dwindle
}

decoration {
    rounding = 10

    #format pour les ombres
    shadow {
        enabled = true
	range = 4
	color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
	size = 3
	passes = 1
    }
}

# 5. ANIMATIONS
animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 3, myBezier
    animation = windowsOut, 1, 3, default, popin 80%
    animation = border, 1, 5, default
    animation = fade, 1, 3, default
    animation = workspaces, 1, 3, default, slide
}

# 6. RACCOURCIS

#raccouris standard
$mainMod = SUPER #touche windows

bind = $mainMod, Q, exec, kitty #ouvre kitty
bind = $mainMod, C, killactive #ferme la fenetre active
bind = $mainMod, M, exit #quitte hyprland
bind = $mainMod, E, exec, nautilus #ouvre le gestionnaire de fichier
bind = $mainMod, V, togglefloating #met la fenetre en mode fenetre
bind = $mainMod, SPACE, exec, rofi -show drun -show-icons #ouvre rofi
bind = ALT, SPACE, exec, ~/.local/bin/rofi-web-search #recherche web

# Navigation entre les fenêtres
bind = $mainMod, left, movefocus, l #deplace la fenetre vers la gauche
bind = $mainMod, right, movefocus, r #deplace la fenetre vers la droite
bind = $mainMod, up, movefocus, u #deplace la fenetre vers le haut
bind = $mainMod, down, movefocus, d #deplace la fenetre vers le bas

# --- WORKSPACES AZERTY ---

# Changer de bureau (Touches &, é, ", ', (, -, è, _, ç, à)
bind = $mainMod, ampersand, workspace, 1
bind = $mainMod, eacute,    workspace, 2
bind = $mainMod, quotedbl,   workspace, 3
bind = $mainMod, apostrophe, workspace, 4
bind = $mainMod, parenleft,  workspace, 5
bind = $mainMod, minus,      workspace, 6
bind = $mainMod, egrave,     workspace, 7
bind = $mainMod, underscore, workspace, 8
bind = $mainMod, ccedilla,   workspace, 9
bind = $mainMod, agrave,     workspace, 10

# Envoyer une fenêtre vers un bureau (SHIFT + la touche)
bind = $mainMod SHIFT, ampersand, movetoworkspace, 1
bind = $mainMod SHIFT, eacute,    movetoworkspace, 2
bind = $mainMod SHIFT, quotedbl,   movetoworkspace, 3
bind = $mainMod SHIFT, apostrophe, movetoworkspace, 4
bind = $mainMod SHIFT, parenleft,  movetoworkspace, 5
bind = $mainMod SHIFT, minus,      movetoworkspace, 6
bind = $mainMod SHIFT, egrave,     movetoworkspace, 7
bind = $mainMod SHIFT, underscore, movetoworkspace, 8
bind = $mainMod SHIFT, ccedilla,   movetoworkspace, 9
bind = $mainMod SHIFT, agrave,     movetoworkspace, 10

# Envoyer la fenêtre active au "Garage" (Minimiser)
bind = $mainMod, MINUS, movetoworkspace, special:magic

# CAPTURES D'ÉCRAN
# mode selection zone
bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy && wl-paste > ~/Images/Screenshots/Screenshot_$(date +%Y%m%d_%H%M%S).png

# Capture full screen
bind = SHIFT, Print, exec, grim - | wl-copy && wl-paste > ~/Images/Screenshots/Full_Screenshot_$(date +%Y%m%d_%H%M%S).png

# Verrouiller l'écran
bind = $mainMod, L, exec, hyprlock

#lancement de waybar
exec-once = pkill waybar; waybar

#curseur
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
